#!/bin/sh

cd `dirname $0`

CONFIG=nextprotload.config

#
#  Function called when the install fails.
#
installFailed ()
{
    echo "Installation Failed: `date`"
    exit 1
}

#
# Make sure the configuration file exists and source it.
#
if [ -r ${CONFIG} ]
then
    echo "Source ${CONFIG}"
    . ${CONFIG}
else
    echo "Cannot source configuration file: ${CONFIG}"
    installFailed
fi

#
# Check to see if this is a development installation.
#
DEV=""
if [ "${INSTALL_TYPE}" = "dev" ]
then
    DEV="-d"
fi

#
# Run DLAInstall.
#
echo 'Running DLAINSTALL'
${DLAINSTALL} ${DEV}

#
# Create the input directory if it doesn't exist.
#
if [ ! -d ${INPUTDIR} ]
then
    mkdir -p ${INPUTDIR}
fi
